version: '3.8'

services:
  db:
    image: postgres:16
    container_name: popwine-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: popwine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: popwine-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db-data:
